---
run:
  timeout: "5m"
output:
  sort-results: true
linters-settings:
  goimports:
    local-prefixes: "github.com/chihaya/chihaya"
  gosec:
    excludes:
      - "G404" # Allow the usage of math/rand
linters:
  enable:
    - "bidichk"
    - "bodyclose"
    - "deadcode"
    - "errcheck"
    - "errname"
    - "errorlint"
    - "gofumpt"
    - "goimports"
    - "goprintffuncname"
    - "gosec"
    - "gosimple"
    - "govet"
    - "ifshort"
    - "importas"
    - "ineffassign"
    - "makezero"
    - "prealloc"
    - "predeclared"
    - "revive"
    - "rowserrcheck"
    - "staticcheck"
    - "structcheck"
    - "stylecheck"
    - "tenv"
    - "typecheck"
    - "unconvert"
    - "unused"
    - "varcheck"
    - "wastedassign"
    - "whitespace"
